version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202111-01
    environment:
      DOCKER_BUILDKIT: 1
      DOCKER_TAG: $DOCKER_TAG
      DOCKER_IMAGE: ruins/mackerel-agent
      BUILDX_PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/arm/v5
    steps:
      - checkout
      - run:
          name: Log in to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Initialize submodule
          command: |
            git submodule update --init
      - run:
          name: Install buildx
          command: |
            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64"

            curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"

            mkdir -p ~/.docker/cli-plugins

            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx

            docker buildx install
      - run:
          name: Build from dockerfile
          command: |
            docker buildx create --use --name build --node build --driver-opt network=host
            docker buildx build . -t ${DOCKER_IMAGE} --platform ${BUILDX_PLATFORMS} --push
