name: kick-workflow-daily
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
    
jobs:
  daily-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check mackerelio repositories
        run: |
          export SHA256_MACKEREL_AGENT=$(git ls-remote -h https://github.com/mackerelio/mackerel-agent | grep master | awk '{ print $1 }')
          export SHA256_MACKEREL_PLUGINS=$(git ls-remote -h https://github.com/mackerelio/mackerel-agent-plugins | grep master | awk '{ print $1 }')
          export SHA256_MACKEREL_CHECK_PLUGINS=$(git ls-remote -h https://github.com/mackerelio/go-check-plugins | grep master | awk '{ print $1 }')
          export SHA256_TOTAL=$(sha256sum "${SHA256_MACKEREL_AGENT}-${SHA256_MACKEREL_PLUGINS}-${SHA256_MACKEREL_CHECK_PLUGINS}")
          curl -L -s 'https://registry.hub.docker.com/v2/repositories/ruins/mackerel-agent/tags' | jq --exit-status ".results[].name | test(\"${SHA256_TOTAL}\")          echo "SKIP=$?" | tee -a $GITHUB_ENV
          echo "SKIP=$?" | tee -a $GITHUB_ENV
          echo "SHA256_TOTAL=${SHA256_TOTAL}" | tee -a $GITHUB_ENV
        shell: bash

      - name: Invoke `latest` workflow
        uses: benc-uk/workflow-dispatch@v1
        if: env.SKIP == 0
        with:
          workflow: latest
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "repos_hash": "env.SHA256_TOTAL" }'

      - name: Invoke `latest-light` workflow
        uses: benc-uk/workflow-dispatch@v1
        if: env.SKIP == 0
        with:
          workflow: latest-light
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "repos_hash": "env.SHA256_TOTAL" }'
  
