name: kick-workflow-daily
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
    
jobs:
  daily-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check mackerelio repositories
        run: |
          echo "HASH_MACKEREL_AGENT=$(git ls-remote -h https://github.com/mackerelio/mackerel-agent | grep master | awk '{ print $1 }')" | tee -a $GITHUB_ENV
          echo "HASH_MACKEREL_PLUGINS=$(git ls-remote -h https://github.com/mackerelio/mackerel-agent-plugins | grep master | awk '{ print $1 }')" | tee -a $GITHUB_ENV
          echo "HASH_MACKEREL_CHECK_PLUGINS=$(git ls-remote -h https://github.com/mackerelio/go-check-plugins | grep master | awk '{ print $1 }')" | tee -a $GITHUB_ENV
        shell: bash
        
      - name: Check unified hash
        run: |
          HASH_TOTAL=$(echo "${HASH_MACKEREL_AGENT}-${HASH_MACKEREL_PLUGINS}-${HASH_MACKEREL_CHECK_PLUGINS}" | sha1sum - | awk '{ print $1 }')
          echo "HASH_TOTAL=${HASH_TOTAL}" | tee -a $GITHUB_ENV
        shell: bash
        
      - name: Check image existance
        run: |
          EXIST=$(curl -L -s 'https://registry.hub.docker.com/v2/repositories/ruins/mackerel-agent/tags' | jq "[.results[].name] | index(\"${HASH_TOTAL}\") >= 0")
          echo "EXIST=${EXIST}" | tee -a $GITHUB_ENV
        shell: bash

      - name: Invoke `latest` workflow
        uses: benc-uk/workflow-dispatch@v1
        if: ${{ env.EXIST == "false" }}
        with:
          workflow: latest-build
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: |
            {
              "docker_tag": "${{ env.HASH_TOTAL }}",
              "hash_mackerel-agent": "${{ env.HASH_MACKEREL_AGENT }}",
              "hash_mackerel-plugins": "${{ env.HASH_MACKEREL_PLUGINS }}",
              "hash_mackerel-check-plugins": "${{ env.HASH_MACKEREL_CHECK_PLUGINS }}"
            }

      - name: Invoke `latest-light` workflow
        uses: benc-uk/workflow-dispatch@v1
        if: ${{ env.EXIST == "false" }}
        with:
          workflow: latest-light-build
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: |
            {
             "docker_tag": "${{ env.HASH_TOTAL }}",
             "hash_mackerel-agent": "${{ env.HASH_MACKEREL_AGENT }}"
            }
