name: kick-workflow-daily
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
    
jobs:
  daily-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check mackerelio repositories
        run: |
          echo "HASH=$(git ls-remote -h https://github.com/mackerelio/mackerel-agent | grep master | awk '{ print $1 }')" | tee -a $GITHUB_ENV
          echo "HASH_MACKEREL_PLUGINS=$(git ls-remote -h https://github.com/mackerelio/mackerel-agent-plugins | grep master | awk '{ print $1 }')" | tee -a $GITHUB_ENV
          echo "HASH_MACKEREL_CHECK_PLUGINS=$(git ls-remote -h https://github.com/mackerelio/go-check-plugins | grep master | awk '{ print $1 }')" | tee -a $GITHUB_ENV
          HASH_TOTAL=$(echo "${SHA256_MACKEREL_AGENT}-${SHA256_MACKEREL_PLUGINS}-${SHA256_MACKEREL_CHECK_PLUGINS}" | sha256sum - | awk '{ print $1 }')
          echo "HASH_TOTAL=${SHA256_TOTAL}" | tee -a $GITHUB_ENV
          EXIST=$(curl -L -s 'https://registry.hub.docker.com/v2/repositories/ruins/mackerel-agent/tags' | jq "[.results[].name] | index(\"${SHA256_TOTAL}\") == 0")
          echo "EXIST=${EXIST}" | tee -a $GITHUB_ENV
        shell: bash

      - name: Invoke `latest` workflow
        uses: benc-uk/workflow-dispatch@v1
        if: ${{ env.EXIST != true }}
        with:
          workflow: latest-build
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: |
          {
            "docker_tag": "${{ env.HASH_TOTAL }}",
            "hash_mackerel-agent": "${{ env.HASH_MACKEREL_AGENT }}",
            "hash_mackerel-plugins": "${{ env.HASH_MACKEREL_PLUGINS }}",
            "hash_mackerel-check-plugins": "${{ env.HASH_MACKEREL_CHECK_PLUGINS }}",
          }

      - name: Invoke `latest-light` workflow
        uses: benc-uk/workflow-dispatch@v1
        if: ${{ env.EXIST != true }}
        with:
          workflow: latest-light-build
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: |
          {
            "docker_tag": "${{ env.HASH_TOTAL }}",
            "hash_mackerel-agent": "${{ env.HASH_MACKEREL_AGENT }}",
          }
