name: latest-build

on:
  workflow_dispatch:
    inputs:
      repos_hash:
        description: "SHA256 of combined string calculated by dependencies"
        required: false
        default: "latest" 
      
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push - latest
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./latest.Dockerfile
          tags: |
            ruins/mackerel-agent:latest
            ruins/mackerel-agent:${{ github.event.inputs.repos_hash }}
          build-args: |
            SHA256_TOTAL=${{ env.SHA256_TOTAL }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
